### PR TITLE
Medicinehistory

### PR DESCRIPTION
**Pull request by navinramsaroop**
Updated medicine view page

### CODE REVIEW

**Comment by AlbertBChung** [comment]
I'm getting an error that reads: Unable to resolve "react-native-swipe-gestures" from "app/screens/MedicineView.js"

Is anyone else getting this error? It breaks my expo and I'm not sure how to fix it

**Comment by navinramsaroop** [comment]
You have to run npm install

**Comment by navinramsaroop** [comment]
I'm going to close this because I want to revert a commit on the settings page, I'll reopen it when I'm done

**Comment by navinramsaroop** [comment]
Okay this should be ready now

For reference: I installed a react native component react-native-swipe-gestures so please do npm install

**Comment by AlbertBChung** [comment]
Yeah i wiped node modules and then ran npm install but it threw an error I didnt know how to fix

**Pull request merged**
