### PR TITLE
Medicinehistory

### PR DESCRIPTION
**Pull request by navinramsaroop**
Redid medicine page

### CODE REVIEW

**Comment by AlbertBChung** [comment]
I have one question.
should we allow user to input the exact time they took the medicine for a past date rather than using the current time?
Im thinking of the scenario where a user correctly takes their medicines and logs it a day later. If the current time is used, the CSV may indicate that they took their medicine late.

**Comment by kavoor** [comment]
> I have one question.
> should we allow user to input the exact time they took the medicine for a past date rather than using the current time?
> Im thinking of the scenario where a user correctly takes their medicines and logs it a day later. If the current time is used, the CSV may indicate that they took their medicine late.

I think if I was a user, I would not want to have to enter the exact time I took the medicine. I either may not remember exactly what time or just dislike the inconvenience of having to enter it. If you had a lot fo pills it would be a lot of extra entering.

**Comment by kavoor** [comment]
Sometimes it doesn't let me take one of the missed medications. Also im not so sure about the yellow

**Comment by navinramsaroop** [comment]
@kavoor Do you know how to reproduce the issue? On my phone it works, so not super sure what's different. If it's red you should always be able to click it.

Also I agree, I don't know if it's important to know the exact time they took the medicationn

**Comment by kavoor** [comment]
> @kavoor Do you know how to reproduce the issue? On my phone it works, so not super sure what's different. If it's red you should always be able to click it.
> 
> Also I agree, I don't know if it's important to know the exact time they took the medication

**Comment by kavoor** [comment]
> @kavoor Do you know how to reproduce the issue? On my phone it works, so not super sure what's different. If it's red you should always be able to click it.
> 
> Also I agree, I don't know if it's important to know the exact time they took the medication

I think I was testing with old DB, looks good to me

**Comment by AlbertBChung** [comment]
I think the medicine sorting is bugged now

**Comment by navinramsaroop** [comment]
Not sure what you mean -- I didn't implement any medicine sorting (it doesn't exist)
It shows up in the order pulled from the database for consistency.
I wanted to avoid the weird cases like one medicine having multiple misses, another having 1 miss, and one saying take now. It's a bit arbitrary which takes priority

I could in the future implement a way of putting the "Done for the day!" cards at the bottom of the list though, but it doesn't affect the functionality

**Comment by AlbertBChung** [comment]
I think we did have medication cards sorting; katy and eashan worked on that. I think a change might have inadvertently affected how the sorting worked. We can talk in our meeting!

**Pull request closed without merging**
